server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/wx_order?characterEncoding=utf-8&useSSL=false
#    username: root
#    password: root

## redis 数据源配置
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

icbc:
  host: https://imapi.icbc.com.cn/open/oauth2
  appid: JUGv88n+aRALNWWKUqXa2Q==